# Generated by Django 2.1.7 on 2019-06-09 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Summarie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Majors.Major')),
            ],
        ),
    ]
