# Generated by Django 2.1.7 on 2019-06-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Majors', '0003_auto_20190609_1145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Summarie',
            new_name='Subject',
        ),
    ]
