# Generated by Django 2.1.7 on 2019-06-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Majors', '0004_auto_20190612_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='major',
            old_name='major_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_major',
            new_name='major',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='name',
        ),
    ]
