# Generated by Django 2.1.7 on 2019-06-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Majors', '0005_auto_20190624_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='mock_exams',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='summaries',
            field=models.URLField(blank=True),
        ),
    ]
